// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as utility$0 from "../utility/models.js";

export function DeleteColsAndRows(model: utility$0.Setting): $CancellablePromise<void> {
    return $Call.ByID(1583274716, model);
}

export function GetMain(): $CancellablePromise<utility$0.Main> {
    return $Call.ByID(2940593569);
}

export function SetHeader(model: utility$0.Setting): $CancellablePromise<void> {
    return $Call.ByID(1241738557, model);
}

export function SetMain(model: utility$0.Main): $CancellablePromise<void> {
    return $Call.ByID(3132490261, model);
}
