// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as utility$0 from "../utility/models.js";

export function GetWorkbook(id: string): $CancellablePromise<utility$0.WorkbookInfo> {
    return $Call.ByID(338056824, id);
}

export function Workbooks(): $CancellablePromise<(utility$0.Workbook | null)[] | null> {
    return $Call.ByID(2674749277);
}
