// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Cell {
    "Value": string;

    /**
     * 是否属于某个合并区域（包括左上角）
     */
    "IsMerged": boolean;
    "ColSpan": number;
    "RowSpan": number;
    "Skip": boolean;
    "Columns": number;
    "StartRow": number;
    "StartCol": number;
    "EndRow": number;
    "EndCol": number;
}

export interface Row {
    "Columns": number;
    "Data": Cell[] | null;
}

export interface Sheet {
    "Name": string;
    "Columns": number;
    "Rows": number;
    "Data": (Row | null)[] | null;
}

export interface Workbook {
    "ID": string;
    "FilePath": string;
    "Name": string;
    "SheetNames": string[] | null;
    "Sheets": { [_ in string]?: Sheet | null } | null;
}

export interface WorkbookInfo {
    "FilePath": string;
    "Name": string;
    "Sheets": (Sheet | null)[] | null;
}

export interface WorkbookMeta {
    "ID": string;
    "FilePath": string;
    "Name": string;
    "SheetNames": string[] | null;
}
